
CREATE USER 'topseven'@'%' IDENTIFIED WITH mysql_native_password; GRANT ALL PRIVILEGES
ON
    *.* TO 'topseven'@'%' REQUIRE NONE WITH
GRANT OPTION MAX_QUERIES_PER_HOUR
    0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
SET PASSWORD FOR
    'topseven'@'%' = PASSWORD('topseven');

CREATE DATABASE IF NOT EXISTS `topseven`; GRANT ALL PRIVILEGES
ON
    `topseven`.* TO 'topseven'@'%';


ALTER DATABASE `topseven` CHARACTER SET utf8 COLLATE utf8_general_ci;
