<?php

$rules = array();
$rules[] = "<h3>Le but du jeu : </h3>\n";
$rules[] = "<li>Remporter le TOP 14 en sélectionnant à chaque journée l'équipe qui vous fera empocher le max de points.</li>\n";
#$rules[] = "<li>Gagner le championnat du TOP 14 en empochant à chaque journée les points obtenus par une équipe de son choix</li>\n";
$rules[] = "<h3>Les règles : </h3>\n";
$rules[] = "<li>7 joueurs. A chaque journée, chacun choisit un match et une équipe et empoche le nombre de points obtenus par celle-ci. Le classement des 7 joueurs (lu à l'envers) permet de définir l'ordre des sélections de la journée suivante.</li>";
$rules[] = "<li>En cas d'égalité, le nombre de matchs gagnés, puis le nombre de victoires à l'extérieur et le nombre d'équipes utilisées serviront à départager.</li>";
$rules[] = "<li>A l'isssue de la saison régulière, les six premiers du TOP 7 participeront à la phase finale en jouant 2 à 2, comme en TOP 14 (d'abord les barrages, puis les 1/2 finales jusqu'à la finale), en donnant un score et le nombre d'essais sur les matchs concernés.</li>";

/*
$rules[] = "<h3>Le but du jeu : </h3>\n";
$rules[] = "<li>Gagner le championnat du TOP 14 en empochant à chaque journée les points obtenus par une équipe de son choix</li>\n";
$rules[] = "<h3>Les règles : </h3>\n";
$rules[] = "<li>Le jeu se compose de 7 joueurs (autant que de rencontres dans une journée de championnat) </li>";
$rules[] = "A chaque journée,";
$rules[] = "<li>Chacun son tour*, dans l'ordre défini par le classement du jeu (du moins bien classé au meilleur, tirage au sort pour la première journée et en cas d'égalités),</li>";
$rules[] = "<li>Chaque joueur sélectionne une équipe (dans une rencontre non déjà sélectionnée par un prédécesseur), celle qui sera susceptible d'empocher le maximum de points à l'issue de son match (jusqu'à 5 points si bonus offensif)</li>";
$rules[] = "<li>Chaque joueur se voit ensuite attribuer les points obtenus par son équipe, agrémentant un classement équivalent à celui du championnat.</li>";
$rules[] = "<li>En cas d'égalités, les critères suivants départageront dans l'ordre les concernés : </li>";
$rules[] = "<li>Nombre de matches gagnés (G), le nombre de victoires à l'extérieur (Ge), le nombre d'équipes utilisées</li>";
$rules[] = "<li>A l'issue des 26 journées de la saison régulière, le 7è du classement sera relégué (au cas où l'on gère différents niveaux, PRO D2, Fédérales),</li>";
$rules[] = "<li>Les 6 premiers disputeront, en pronostics deux à deux, les phases finales (barrages, demies et finale) avec le principe suivant :</li>";
$rules[] = "Chacun donne un score et le nombre d'essais total de la rencontre qui correspond à son classement et le plus proche se qualifie à la phase suivante ou remporte le championnat, exactement comme ce sera le cas pour les équipes du TOP 14.</li>";

$rules[] = "<br><br>(*) Chacun devra attendre, ";
$rules[] = "<li>soit que tous ses prédécesseurs aient fait leurs choix</li>";
$rules[] = "<li>soit que la date/heure indiquée en face de son nom arrive à échéance, </li>";
$rules[] = "Auquel second cas, les privilégiés retardataires feront leurs choix avec ce qu’il restera, et ce jusqu’au jeudi soir.";
 */

$manual = array();
$manual[] ="<li>Quand c'est à vous de jouer le bouton orange 'Prono' apparait en haut à gauche.</li>";
$manual[] ="<li>Selectionner votre équipe et valider votre prono avec le bouton rouge.</li>";
?>
